<?php

/*
 * Page for displaying vote administration tab pages.
 */

function advpoll_votes_page () {
    return 'votes page';
}

function advpoll_electoral_list_page() {
    return 'electoral list';
}

function advpoll_remove_voter() {
    return 'remove voter';
}

function advpoll_clear_votes_page() {
    return 'clear votes';
}

function advpoll_writeins_page() {
    return 'write-ins page';
}

function advpoll_results_page() {
    return 'results page';
}